listagem =  {'Misto-Quente': 3,
             'Cachorro-Quente': 4.5, 
             'Coxinha': 3, 
             'Hamburgão': 3.5, 
             'X-Burguer': 6,
             'X-Salada': 7.5, 
             'X-Tudo': 14, 
             'Refrigerante': 4.5, 
             'Suco': 3.5, 
             'Água': 2, 
             'Água c/Gás': 2, 
             'Café': 3, 
             'Café c/Leite': 3,
             'Batata Frita': 14,
             'Bauru': 3,}
